plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.16'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'io.freefair.lombok' version '8.0.1'
}

group = 'bankster'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
//    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
//    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'org.bytedeco:openblas-platform:0.3.23-1.5.9'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation 'com.amazonaws:aws-java-sdk-dynamodb:1.10.52'
    implementation 'com.github.derjust:spring-data-dynamodb:4.2.0'
    implementation 'org.json:json:20240303'

    implementation 'com.github.haifengl:smile-core:2.6.0'
    implementation 'com.github.haifengl:smile-data:2.6.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'
//    runtimeOnly 'org.springframework.boot-devtools'
//    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
