plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.16'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'io.freefair.lombok' version '8.0.1'
}

group = 'bankster'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }

}

dependencies {
    // Smile ML
    implementation 'com.github.haifengl:smile-core:2.6.0'
    implementation 'com.github.haifengl:smile-data:2.6.0'
    implementation 'com.github.haifengl:smile-math:2.6.0'

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // DL4J / ND4J
    implementation 'org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1'
//    implementation 'org.nd4j:nd4j-native-platform:1.0.0-M2.1'

    // Other deps
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'org.json:json:20240303'
    implementation 'io.netty:netty-resolver-dns-native-macos:4.1.99.Final:osx-aarch_64' // for Apple Silicon


    implementation("org.nd4j:nd4j-native:1.0.0-M2.1")
    // For M1 apple processor
    implementation("org.nd4j:nd4j-native:1.0.0-M2.1:macosx-arm64")
    implementation("org.bytedeco:openblas:0.3.21-1.5.8:macosx-arm64")
}
